In [1]:
pip install pandas


[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd

c:\Users\rachi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\rachi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\rachi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
df1=pd.read_csv("project_sal.csv")


In [4]:
df1

YearsExperience  Projects  Salary
0               1.1         1   39343
1               1.3         2   46205
2               1.5         1   37731
3               2.0         2   43525
4               2.2         1   39891
5               2.9         4   56642
6               3.0         4   60150
7               3.2         3   54445
8               3.2         5   64445
9               3.7         2   57189
10              3.9         4   63218
11              4.0         7   55794
12              4.0         8   56957
13              4.1         8   57081
14              4.5         9   61111
15              4.9        10   67938
16              5.1         8   66029
17              5.3        11   83088
18              5.9         9   81363
19              6.0        12   93940
20              6.8         6   91738
21              7.1         7   98273
22              7.9        11  101302
23              8.2         6  113812
24              8.7         5  109431
25              9.0         5  105582
26              9.5         6  116969
27              9.6         8  112635
28             10.3        10  122391
29             10.5        11  121872
30             11.2         4  127345
31             11.5         8  126756
32             12.3         7  128765
33             12.9         5  135675
34             13.5         9  139465

In [5]:
x1=df1.iloc[:,:-1].values
x1

array([[ 1.1,  1. ],
       [ 1.3,  2. ],
       [ 1.5,  1. ],
       [ 2. ,  2. ],
       [ 2.2,  1. ],
       [ 2.9,  4. ],
       [ 3. ,  4. ],
       [ 3.2,  3. ],
       [ 3.2,  5. ],
       [ 3.7,  2. ],
       [ 3.9,  4. ],
       [ 4. ,  7. ],
       [ 4. ,  8. ],
       [ 4.1,  8. ],
       [ 4.5,  9. ],
       [ 4.9, 10. ],
       [ 5.1,  8. ],
       [ 5.3, 11. ],
       [ 5.9,  9. ],
       [ 6. , 12. ],
       [ 6.8,  6. ],
       [ 7.1,  7. ],
       [ 7.9, 11. ],
       [ 8.2,  6. ],
       [ 8.7,  5. ],
       [ 9. ,  5. ],
       [ 9.5,  6. ],
       [ 9.6,  8. ],
       [10.3, 10. ],
       [10.5, 11. ],
       [11.2,  4. ],
       [11.5,  8. ],
       [12.3,  7. ],
       [12.9,  5. ],
       [13.5,  9. ]])

In [6]:
y1=df1.iloc[:,-1].values
y1

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872, 127345, 126756,
       128765, 135675, 139465], dtype=int64)

In [7]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
model1=LinearRegression()

In [11]:
model1.fit(x1,y1)

LinearRegression()

In [12]:
model1.predict([[3,3]])

array([54426.57824778])

In [13]:
model1.predict([[1.1,1]])

array([37431.5689382])

In [14]:
df = pd.read_csv(r"C:\Users\rachi\Desktop\py\Machine\iris.csv")
df.describe


<bound method NDFrame.describe of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [15]:
df.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

In [16]:
from sklearn.datasets import load_iris

In [17]:
data=load_iris()
X=data['data']
data

In [18]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [19]:
Y=data['target']

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
model=KNeighborsClassifier()

In [22]:
model.fit(X,Y)

KNeighborsClassifier()

In [23]:
X_pred=model.predict(X)
X_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
model.predict([[3.4,1.3,2,6.1]])

array([1])

In [25]:
from sklearn.metrics import accuracy_score

In [26]:
accuracy_score(X_pred,Y)

0.9666666666666667

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
confusion_matrix(Y,X_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  2, 48]], dtype=int64)

In [29]:
from sklearn.metrics import classification_report

In [30]:
print(classification_report(Y,X_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.96      0.94      0.95        50
           2       0.94      0.96      0.95        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150



In [31]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
f=pd.read_csv(r"C:\Users\rachi\Desktop\py\Machine\Fruit_dataset_10000.csv")
X2=f.iloc[0::1,1::1].values
y2=f.iloc[0::1,0].values
X_train,X_test,Y_train,Y_test=train_test_split(X2,y2)
print(len(X_train))
print(len(Y_train))
model2=KNeighborsClassifier()
model2.fit(X_train,Y_train)
y_pred= model2.predict(X_train)
accuracy_score(Y_train,y_pred)
y_test_pred=model2.predict(X_test)
accuracy_score(Y_test,y_test_pred)

7500
7500


0.96